# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(435, 465)
        MainWindow.setMinimumSize(QtCore.QSize(435, 465))
        MainWindow.setMaximumSize(QtCore.QSize(435, 465))
        MainWindow.setInputMethodHints(QtCore.Qt.ImhDate|QtCore.Qt.ImhPreferUppercase)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setEnabled(True)
        self.comboBox.setMinimumSize(QtCore.QSize(140, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(140, 16777215))
        self.comboBox.setEditable(False)
        self.comboBox.setMaxVisibleItems(10)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(4, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.minusButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.minusButton_3.setMaximumSize(QtCore.QSize(50, 50))
        self.minusButton_3.setObjectName("minusButton_3")
        self.gridLayout.addWidget(self.minusButton_3, 17, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 19, 0, 1, 1)
        self.plusButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.plusButton_5.setMaximumSize(QtCore.QSize(50, 50))
        self.plusButton_5.setObjectName("plusButton_5")
        self.gridLayout.addWidget(self.plusButton_5, 19, 3, 1, 1)
        self.plusButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.plusButton_1.setMaximumSize(QtCore.QSize(50, 50))
        self.plusButton_1.setObjectName("plusButton_1")
        self.gridLayout.addWidget(self.plusButton_1, 13, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 13, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 11, 0, 1, 1)
        self.plusButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.plusButton_6.setMaximumSize(QtCore.QSize(50, 50))
        self.plusButton_6.setObjectName("plusButton_6")
        self.gridLayout.addWidget(self.plusButton_6, 20, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 18, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 17, 0, 1, 1)
        self.minusButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.minusButton_2.setMaximumSize(QtCore.QSize(50, 50))
        self.minusButton_2.setObjectName("minusButton_2")
        self.gridLayout.addWidget(self.minusButton_2, 16, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 20, 0, 1, 1)
        self.minusButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.minusButton_0.setMaximumSize(QtCore.QSize(50, 50))
        self.minusButton_0.setObjectName("minusButton_0")
        self.gridLayout.addWidget(self.minusButton_0, 11, 1, 1, 1)
        self.minusButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.minusButton_5.setMaximumSize(QtCore.QSize(50, 50))
        self.minusButton_5.setObjectName("minusButton_5")
        self.gridLayout.addWidget(self.minusButton_5, 19, 1, 1, 1)
        self.minusButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.minusButton_1.setMaximumSize(QtCore.QSize(50, 50))
        self.minusButton_1.setObjectName("minusButton_1")
        self.gridLayout.addWidget(self.minusButton_1, 13, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 16, 0, 1, 1)
        self.plusButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.plusButton_4.setMaximumSize(QtCore.QSize(50, 50))
        self.plusButton_4.setObjectName("plusButton_4")
        self.gridLayout.addWidget(self.plusButton_4, 18, 3, 1, 1)
        self.lineEdit_0 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_0.setFont(font)
        self.lineEdit_0.setMaxLength(3)
        self.lineEdit_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_0.setObjectName("lineEdit_0")
        self.gridLayout.addWidget(self.lineEdit_0, 11, 2, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setMaxLength(3)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 19, 2, 1, 1)
        self.plusButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.plusButton_0.setMaximumSize(QtCore.QSize(50, 50))
        self.plusButton_0.setObjectName("plusButton_0")
        self.gridLayout.addWidget(self.plusButton_0, 11, 3, 1, 1)
        self.plusButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.plusButton_3.setMaximumSize(QtCore.QSize(50, 50))
        self.plusButton_3.setObjectName("plusButton_3")
        self.gridLayout.addWidget(self.plusButton_3, 17, 3, 1, 1)
        self.minusButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.minusButton_4.setMaximumSize(QtCore.QSize(50, 50))
        self.minusButton_4.setObjectName("minusButton_4")
        self.gridLayout.addWidget(self.minusButton_4, 18, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setMaxLength(3)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 18, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 22, 0, 1, 4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setMaxLength(3)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 16, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setMaxLength(3)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 17, 2, 1, 1)
        self.plusButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.plusButton_2.setMaximumSize(QtCore.QSize(50, 50))
        self.plusButton_2.setObjectName("plusButton_2")
        self.gridLayout.addWidget(self.plusButton_2, 16, 3, 1, 1)
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setMaxLength(3)
        self.lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout.addWidget(self.lineEdit_1, 13, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 9, 0, 1, 4)
        self.minusButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.minusButton_6.setMaximumSize(QtCore.QSize(50, 50))
        self.minusButton_6.setObjectName("minusButton_6")
        self.gridLayout.addWidget(self.minusButton_6, 20, 1, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setMaxLength(3)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 20, 2, 1, 1)
        self.summEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.summEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.summEdit.setFont(font)
        self.summEdit.setObjectName("summEdit")
        self.gridLayout.addWidget(self.summEdit, 23, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 25, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 23, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 24, 0, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 435, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.statusBar.setFont(font)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action545 = QtWidgets.QAction(MainWindow)
        self.action545.setObjectName("action545")
        self.action54 = QtWidgets.QAction(MainWindow)
        self.action54.setObjectName("action54")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.menu.addAction(self.action_6)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox, self.lineEdit_0)
        MainWindow.setTabOrder(self.lineEdit_0, self.lineEdit_1)
        MainWindow.setTabOrder(self.lineEdit_1, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.minusButton_0)
        MainWindow.setTabOrder(self.minusButton_0, self.minusButton_1)
        MainWindow.setTabOrder(self.minusButton_1, self.minusButton_2)
        MainWindow.setTabOrder(self.minusButton_2, self.minusButton_3)
        MainWindow.setTabOrder(self.minusButton_3, self.minusButton_4)
        MainWindow.setTabOrder(self.minusButton_4, self.minusButton_5)
        MainWindow.setTabOrder(self.minusButton_5, self.minusButton_6)
        MainWindow.setTabOrder(self.minusButton_6, self.plusButton_0)
        MainWindow.setTabOrder(self.plusButton_0, self.plusButton_1)
        MainWindow.setTabOrder(self.plusButton_1, self.plusButton_2)
        MainWindow.setTabOrder(self.plusButton_2, self.plusButton_3)
        MainWindow.setTabOrder(self.plusButton_3, self.plusButton_4)
        MainWindow.setTabOrder(self.plusButton_4, self.plusButton_5)
        MainWindow.setTabOrder(self.plusButton_5, self.plusButton_6)
        MainWindow.setTabOrder(self.plusButton_6, self.summEdit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Счётчик багов"))
        self.label_3.setText(_translate("MainWindow", "Фамилия"))
        self.minusButton_3.setText(_translate("MainWindow", "-"))
        self.label_7.setText(_translate("MainWindow", "Не баг/дубль"))
        self.plusButton_5.setText(_translate("MainWindow", "+"))
        self.plusButton_1.setText(_translate("MainWindow", "+"))
        self.label_2.setText(_translate("MainWindow", "Критичный второй категории"))
        self.label.setText(_translate("MainWindow", "Критичный первой категории"))
        self.plusButton_6.setText(_translate("MainWindow", "+"))
        self.label_9.setText(_translate("MainWindow", "Простейший"))
        self.label_8.setText(_translate("MainWindow", "Некритичный второй категории"))
        self.minusButton_2.setText(_translate("MainWindow", "-"))
        self.label_6.setText(_translate("MainWindow", "Некорректный"))
        self.minusButton_0.setText(_translate("MainWindow", "-"))
        self.minusButton_5.setText(_translate("MainWindow", "-"))
        self.minusButton_1.setText(_translate("MainWindow", "-"))
        self.label_5.setText(_translate("MainWindow", "Некритичный первой категории"))
        self.plusButton_4.setText(_translate("MainWindow", "+"))
        self.lineEdit_0.setText(_translate("MainWindow", "0"))
        self.lineEdit_5.setText(_translate("MainWindow", "0"))
        self.plusButton_0.setText(_translate("MainWindow", "+"))
        self.plusButton_3.setText(_translate("MainWindow", "+"))
        self.minusButton_4.setText(_translate("MainWindow", "-"))
        self.lineEdit_4.setText(_translate("MainWindow", "0"))
        self.pushButton.setText(_translate("MainWindow", "Сгенерировать отчёт"))
        self.lineEdit_2.setText(_translate("MainWindow", "0"))
        self.lineEdit_3.setText(_translate("MainWindow", "0"))
        self.plusButton_2.setText(_translate("MainWindow", "+"))
        self.lineEdit_1.setText(_translate("MainWindow", "0"))
        self.minusButton_6.setText(_translate("MainWindow", "-"))
        self.lineEdit_6.setText(_translate("MainWindow", "0"))
        self.pushButton_2.setText(_translate("MainWindow", "Очистить"))
        self.label_4.setText(_translate("MainWindow", "Итого багов"))
        self.menu.setTitle(_translate("MainWindow", "Опции"))
        self.action545.setText(_translate("MainWindow", "545"))
        self.action54.setText(_translate("MainWindow", "54"))
        self.action_3.setText(_translate("MainWindow", "Добавить"))
        self.action_4.setText(_translate("MainWindow", "Изменить"))
        self.action_5.setText(_translate("MainWindow", "Удалить"))
        self.action_6.setText(_translate("MainWindow", "Управление тестировщиками"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

